"""initial schema

Revision ID: 6e7e9bde2772
Revises:
Create Date: 2026-03-14 14:44:18.881926

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e7e9bde2772"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Note: BudgetCategory, ChatMessageRecord, and FinancialHealthScore are
    # client-only SwiftData models (not synced to backend). They are intentionally
    # absent from this migration.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("apple_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_apple_id"), "users", ["apple_id"], unique=True)
    op.create_table(
        "accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("plaid_account_id", sa.String(length=255), nullable=True),
        sa.Column("plaid_access_token", sa.String(length=255), nullable=True),
        sa.Column("plaid_item_id", sa.String(length=255), nullable=True),
        sa.Column("plaid_cursor", sa.String(length=255), nullable=True),
        sa.Column("institution_name", sa.String(length=255), nullable=False),
        sa.Column("account_name", sa.String(length=255), nullable=False),
        sa.Column("account_type", sa.String(length=20), nullable=False),
        sa.Column("current_balance", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("available_balance", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("is_manual", sa.Boolean(), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_accounts_user_type", "accounts", ["user_id", "account_type"], unique=False)
    op.create_table(
        "financial_goals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("goal_name", sa.String(length=255), nullable=False),
        sa.Column("goal_type", sa.String(length=20), nullable=False),
        sa.Column("target_amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("current_amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("target_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("monthly_contribution", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "net_worth_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_assets", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("total_liabilities", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_net_worth_snapshots_user_date",
        "net_worth_snapshots",
        ["user_id", "date"],
        unique=False,
    )
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("date_of_birth", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("annual_income", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("monthly_expenses", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("filing_status", sa.String(length=30), nullable=False),
        sa.Column("state_of_residence", sa.String(length=2), nullable=True),
        sa.Column("retirement_age", sa.Integer(), nullable=False),
        sa.Column("risk_tolerance", sa.String(length=20), nullable=False),
        sa.Column("dependents", sa.Integer(), nullable=False),
        sa.Column("has_spouse", sa.Boolean(), nullable=False),
        sa.Column("spouse_income", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index("ix_user_profiles_user_id", "user_profiles", ["user_id"], unique=False)
    op.create_table(
        "debts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("debt_name", sa.String(length=255), nullable=False),
        sa.Column("debt_type", sa.String(length=20), nullable=False),
        sa.Column("original_balance", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("current_balance", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("interest_rate", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("minimum_payment", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("payoff_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("is_fixed_rate", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "investment_holdings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("security_name", sa.String(length=255), nullable=False),
        sa.Column("ticker_symbol", sa.String(length=20), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("cost_basis", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("current_price", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("holding_type", sa.String(length=20), nullable=False),
        sa.Column("asset_class", sa.String(length=20), nullable=False),
        sa.Column("purchase_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_price_update", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("plaid_transaction_id", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("date", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("merchant_name", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("subcategory", sa.String(length=100), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("is_recurring", sa.Boolean(), nullable=False),
        sa.Column("is_pending", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_transactions_account_date",
        "transactions",
        ["account_id", "date"],
        unique=False,
    )
    # Uniqueness for plaid_transaction_id is enforced at the application upsert
    # layer, not the database.  Plaid can send modified transactions with the
    # same ID, so a unique index would cause constraint violations on re-sync.
    op.create_index(
        op.f("ix_transactions_plaid_transaction_id"),
        "transactions",
        ["plaid_transaction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_plaid_transaction_id"), table_name="transactions")
    op.drop_index("ix_transactions_account_date", table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("investment_holdings")
    op.drop_table("debts")
    op.drop_index("ix_user_profiles_user_id", table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index("ix_net_worth_snapshots_user_date", table_name="net_worth_snapshots")
    op.drop_table("net_worth_snapshots")
    op.drop_table("financial_goals")
    op.drop_index("ix_accounts_user_type", table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_users_apple_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
